import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { readex } from "@/assets/font";
import AuthTokenProvider from "./_Compontents/Authtoken/Authtoken";
import { PackageProvider } from "./_Compontents/PackageContext/PackageContext";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: "Tajwal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="ar">
      <head>
        <link rel="icon" href="/footerHero.svg" />
        <script id='ze-snippet' src='https://static.zdassets.com/ekr/snippet.js?key=f4e36963-4fc1-4a3c-9fca-282829bb25e1'> </script>
      </head>
      <body className={`${readex.className} antialiased`}>
        <AuthTokenProvider>
          <PackageProvider>
            <Toaster />
            {children}
          </PackageProvider>
        </AuthTokenProvider>
      </body>
    </html>
  );
}
